version: 2
updates:
  - package-ecosystem: terraform
    directory: "/deploy/aws/pre-infra"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: terraform
    directory: "/deploy/aws/infra"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
