charts:
  - name: aws-auth-config
    namespace: kube-system
    location: ./deploy/helm/charts
    enabled: true
    values_template: deploy/helm/values/aws_auth_config.yaml

  - name: cert-manager
    namespace: ${env:CERT_MANAGER_NAMESPACE}
    location: cert-manager
    enabled: "${env:CERT_MANAGER_ENABLED}"
    repo: https://charts.jetstack.io
    values_template: deploy/helm/values/cert_manager.yaml
    version: v1.18.2

  - name: cert-manager-default-tls
    # We want to deploy the Issuer, Secret, and Cert into the Nginx Namespace
    namespace: ${env:INGRESS_NGINX_NAMESPACE}
    location: ./deploy/helm/charts
    enabled: ${env:CERT_MANAGER_ENABLED}
    values_template: deploy/helm/values/cert_manager_default_tls.yaml

  # NOTE: This project is now archived
  - name: hierarchical-namespaces
    namespace: hierarchical-namespaces
    location: https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0/default.yaml
    versioning_regex: v([0-9.]+)
    enabled: false
    wrap_raw_yaml: true

  - name: ingress-nginx
    namespace: ${env:INGRESS_NGINX_NAMESPACE}
    location: ingress-nginx
    enabled: "${env:INGRESS_NGINX_ENABLED}"
    repo: https://kubernetes.github.io/ingress-nginx
    values_template: deploy/helm/values/ingress_nginx.yaml
    version: 4.13.3

  - name: external-dns
    namespace: external-dns
    location: external-dns
    enabled: "${env:EXTERNAL_DNS_ENABLED}"
    repo: https://kubernetes-sigs.github.io/external-dns/
    values_template: deploy/helm/values/external_dns.yaml
    version: 1.19.0

  - name: bottlerocket-cis-validation
    namespace: bottlerocket-cis-validation
    location: ./deploy/helm/charts
    enabled: "${env:BOTTLEROCKET_CIS_VALIDATION_JOB_ENABLED}"
    values_template: deploy/helm/values/bottlerocket_cis_validation.yaml

  - name: kyverno
    namespace: kyverno
    location: kyverno
    enabled: "${env:KYVERNO_ENABLED}"
    repo: https://kyverno.github.io/kyverno/
    values_template: deploy/helm/values/kyverno.yaml
    version: 3.5.2

  - name: kyverno-policies
    namespace: kyverno-policies
    location: ./deploy/helm/charts
    enabled: "${env:KYVERNO_POLICIES_ENABLED}"
    values_template: deploy/helm/values/kyverno-policies.yaml

  - name: aws-ebs-csi-driver
    namespace: ${env:AWS_EBS_CSI_DRIVER_NAMESPACE}
    location: aws-ebs-csi-driver
    enabled: "${env:AWS_EBS_CSI_DRIVER_ENABLED}"
    repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    values_template: deploy/helm/values/aws-ebs-csi-driver.yaml
    version: 2.49.1
