apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-{{ .Values.certificate.dnsName }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    kind: Issuer
    name: {{ .Values.issuer.name }}
  dnsNames:
    - "*.{{ .Values.certificate.dnsName }}"
