# A map from Terraform Outputs in the following structure:
# {
#   "administrators": {
#     "role_name": "Administrators",
#     "role_prefix": "arn:aws:sts::<ACCOUNT_ID>:assumed-role/Okta-Ensono-Digital",
#     "max_session_duration": 14400,
#     "k8s_group_name": "system:masters",
#     "users": [
#       "Jack.Blower@ensono.com"
#     ],
#     "mapped_users": [
#       arn:aws:sts::123456789:assumed-role/Okta-Ensono-Digital/"Jack.Blower@ensono.com""
#     ],
#     "role_arn": "arn:..."
#   }
# }
k8s_roles: {}
