app:
  name: echo-test
  image: hashicorp/http-echo
  text: "hello from the cluster!"
  replicas: 1
  port: 5678

gateway:
  name: traefik-gateway
  namespace: traefik
  sectionName: websecure

hostname: sloe.nonprod.aws.stacks.ensono.com
