provider: aws

env:
  - name: AWS_DEFAULT_REGION
    value: ${env:REGION}

serviceAccount:
  create: true
  name: "${env:EXTERNAL_DNS_SERVICE_ACCOUNT_NAME}"
  annotations: 
    eks.amazonaws.com/role-arn: "${env:TFOUT_external_dns_role_arn}"

podSecurityContext:
  fsGroup: 1001