controller:
  kind: Deployment
  replicaCount: "${env:INGRESS_NGINX_REPLICA_COUNT}"
  service:
    type: LoadBalancer
    omitClusterIP: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "${env:TFOUT_aws_public_subnets_comma_string}"
  publishService:
    enabled: true
  stats:
    enabled: true
    service:
      omitClusterIP: true
  tolerations:
    - key: "WorkerAttachedToExtLoadBalancer"
      operator: "Exists"
      effect: "NoSchedule"
  extraArgs:
    default-ssl-certificate: ${env:INGRESS_NGINX_NAMESPACE}/default-tls-secret
defaultBackend:
  service:
    omitClusterIP: true
