name: air.stacks-infrastructure-eks

on:
  push:
    paths:
      - 'build/github/**'
      - 'build/taskctl/**'
      - 'src/**'
      - 'deploy/aws/**'
      - 'deploy/k8s/aws/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - master
      - main

env:
  # The following SECRETS are required in your GH Repository:
  #   PACT_BEARER_TOKEN
  #   SONAR_TOKEN
  # The following SECRETS must be defined per environment (which must match environment key) in your GH Repository:
  #   AWS_ACCESS_KEY_ID
  #   AWS_ACCOUNT_ID
  #   AWS_DEFAULT_REGION
  #   AWS_SECRET_ACCESS_KEY
  #   AWS_TF_STATE_BUCKET
  #   AWS_TF_STATE_DYNAMOTABLE
  #   AWS_TF_STATE_ENCRYPTION
  #   AWS_TF_STATE_KEY
  #   AWS_TF_STATE_REGION
  CLOUD_PROVIDER: "aws"
  TaskctlVersion: '1.4.2'
  COMPANY: "ensono"
  PROJECT: "stacks"
  COMPONENT: "eks"
  REGION: "eu-west-2"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_FILE_LOCATION: deploy/aws/stacks-eks
  NON_PROD_BASE_DOMAIN_NAME: "nonprod.aws.stacks.ensono.com"
  PROD_BASE_DOMAIN_NAME: "prod.aws.stacks.ensono.com"
  # AWS LB Controller Helm
  AWS_LB_CONTROLLER_ENABLED: true
  AWS_LB_CONTROLLER_NAMESPACE: "aws-lb-controller"
  AWS_LB_CONTROLLER_SERVICE_ACCOUNT_NAME: "aws-lb-controller"
  # External DNS Helm
  EXTERNAL_DNS_ENABLED: true
  EXTERNAL_DNS_NAMESPACE: "external-dns"
  EXTERNAL_DNS_SERVICE_ACCOUNT_NAME: "external-dns"

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./build/github/templates/install-taskctl
      - run: taskctl -d lint
        env:
          TF_FILE_LOCATION: ${{ env.TF_FILE_LOCATION }}

  InfraDev:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
    needs: Lint
    runs-on: ubuntu-latest
    environment: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./build/github/templates/install-taskctl
      # TODO: This is tactical, will require refactor of task to take arguments as separate var
      - run: taskctl -d infrastructure
        env:
          ENV_NAME: nonprod
          # AWS Environmental Config
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.REGION }}
          # Terraform Backend Configuration
          AWS_TF_STATE_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET }}
          AWS_TF_STATE_DYNAMOTABLE: ${{ secrets.AWS_TF_STATE_DYNAMOTABLE }}
          AWS_TF_STATE_ENCRYPTION: ${{ secrets.AWS_TF_STATE_ENCRYPTION }}
          AWS_TF_STATE_KEY: ${{ secrets.AWS_TF_STATE_KEY }}
          AWS_TF_STATE_REGION: ${{ secrets.AWS_TF_STATE_REGION }}
          TF_FILE_LOCATION: ${{ env.TF_FILE_LOCATION }}
          TF_BACKEND_ARGS: region=${{ secrets.AWS_TF_STATE_REGION }},access_key=${{ secrets.AWS_ACCESS_KEY_ID }},secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }},bucket=${{ secrets.AWS_TF_STATE_BUCKET }},key=${{ secrets.AWS_TF_STATE_KEY }},dynamodb_table=${{ secrets.AWS_TF_STATE_DYNAMOTABLE }},encrypt=${{ secrets.AWS_TF_STATE_ENCRYPTION }}
          # Terraform Resource Configuration
          TF_VAR_name_environment: "nonprod"
          TF_VAR_name_company: ${{ env.COMPANY }}
          TF_VAR_name_project: ${{ env.PROJECT }}
          TF_VAR_name_component: ${{ env.COMPONENT }}
          TF_VAR_region: ${{ env.REGION }}
          TF_VAR_dns_hostedzone_name: "${{ env.NON_PROD_BASE_DOMAIN_NAME }}"
          TF_VAR_enable_zone: true
          TF_VAR_manage_aws_auth_configmap: true
          TF_VAR_external_dns_enabled: "${{ env.EXTERNAL_DNS_ENABLED }}"
          TF_VAR_external_dns_namespace: "${{ env.EXTERNAL_DNS_NAMESPACE }}"
          TF_VAR_external_dns_service_account_name: "${{ env.EXTERNAL_DNS_SERVICE_ACCOUNT_NAME }}"
          TF_VAR_aws_lb_controller_enabled: ${{ env.AWS_LB_CONTROLLER_ENABLED }}
          TF_VAR_aws_lb_controller_namespace: "${{ env.AWS_LB_CONTROLLER_NAMESPACE }}"
          TF_VAR_aws_lb_controller_service_account_name: "${{ env.AWS_LB_CONTROLLER_SERVICE_ACCOUNT_NAME }}"

  InfraProd:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    needs: Lint
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./build/github/templates/install-taskctl
      # TODO: This is tactical, will require refactor of task to take arguments as separate var
      - run: taskctl -d infrastructure
        env:
          ENV_NAME: prod
          # AWS Environmental Config
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.REGION }}
          # Terraform Backend Configuration
          AWS_TF_STATE_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET }}
          AWS_TF_STATE_DYNAMOTABLE: ${{ secrets.AWS_TF_STATE_DYNAMOTABLE }}
          AWS_TF_STATE_ENCRYPTION: ${{ secrets.AWS_TF_STATE_ENCRYPTION }}
          AWS_TF_STATE_KEY: ${{ secrets.AWS_TF_STATE_KEY }}
          AWS_TF_STATE_REGION: ${{ secrets.AWS_TF_STATE_REGION }}
          TF_FILE_LOCATION: ${{ env.TF_FILE_LOCATION }}
          TF_BACKEND_ARGS: region=${{ secrets.AWS_TF_STATE_REGION }},access_key=${{ secrets.AWS_ACCESS_KEY_ID }},secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }},bucket=${{ secrets.AWS_TF_STATE_BUCKET }},key=${{ secrets.AWS_TF_STATE_KEY }},dynamodb_table=${{ secrets.AWS_TF_STATE_DYNAMOTABLE }},encrypt=${{ secrets.AWS_TF_STATE_ENCRYPTION }}
          # Terraform Resource Configuration
          TF_VAR_name_environment: "prod"
          TF_VAR_name_company: ${{ env.COMPANY }}
          TF_VAR_name_project: ${{ env.PROJECT }}
          TF_VAR_name_component: ${{ env.COMPONENT }}
          TF_VAR_region: ${{ env.REGION }}
          TF_VAR_dns_hostedzone_name: "${{ env.PROD_BASE_DOMAIN_NAME }}"
          TF_VAR_enable_zone: true
          TF_VAR_external_dns_enabled: "${{ env.EXTERNAL_DNS_ENABLED }}"
          TF_VAR_external_dns_namespace: "${{ env.EXTERNAL_DNS_NAMESPACE }}"
          TF_VAR_external_dns_service_account_name: "${{ env.EXTERNAL_DNS_SERVICE_ACCOUNT_NAME }}"
